/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import control.Tabla;
import javax.swing.ImageIcon;

/**
 *
 * @author Flayxamax
 */
public class dlgPuntuaciones extends javax.swing.JDialog {

    /**
     * Constructor de ventana de puntuaciones que recibe tabla de puntaje
     * 
     * @param parent Parent
     * @param modal Modal
     * @param tabla Tabla
     */
    public dlgPuntuaciones(java.awt.Frame parent, boolean modal, Tabla tabla) {
        super(parent, modal);
        initComponents();
        despliegaTabla(tabla);
        setResizable(false);
        setTitle("Clasificación de puntajes");
        setIconImage(new ImageIcon(getClass().getResource("/img/iconGame.png")).getImage());
    }

    public void despliegaTabla(Tabla tabla) {
    // Crea la tabla a partir del modelo de la tabla con los valores
    // de los titulos de las columnas y los valores de las celdas
    jtabla = new javax.swing.JTable(tabla.getModeloTabla());
    // Establece el título de la tabla
    // Hace que el control del tamaño de la tabla y la porción visible
    // lo tenga la barra de deslizamiento y no la tabla
    jtabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    jtabla.setAutoscrolls(false);
    // Hace visible la tabla dentro del panel con barras de
    // deslizamiento
    jScrollPane1.setViewportView(jtabla);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lblTitulo = new javax.swing.JLabel();
        lblTrofeo = new javax.swing.JLabel();
        lblLBFondo = new javax.swing.JLabel();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setAlignmentY(5.0F);
        jScrollPane1.setNextFocusableComponent(this);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 344));

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lblpun.png"))); // NOI18N
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, -1));

        lblTrofeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trophy.gif"))); // NOI18N
        getContentPane().add(lblTrofeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        lblLBFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leader.png"))); // NOI18N
        getContentPane().add(lblLBFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 412));

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leaderbg.gif"))); // NOI18N
        getContentPane().add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private javax.swing.JTable jtabla;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblLBFondo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTrofeo;
    // End of variables declaration//GEN-END:variables
}
