/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import control.CustomFont;
import java.applet.AudioClip;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Flayxamax
 */
public class FAQ extends javax.swing.JFrame {

    /**
     * Creates new form FAQ
     */
    public FAQ() {
        initComponents();
        setResizable(false);
        setTitle("FREQUENTLY ASKED QUESTIONS");
        setIconImage(new ImageIcon(getClass().getResource("/img/iconGame.png")).getImage());
        setSize(1000, 650);
        CustomFont cf = new CustomFont();
        boxOp.setFont(cf.MyFont(0, 30));

        ImageIcon cartel = new ImageIcon(getClass().getResource("/img/cartel1.png"));
        lblCartel.setIcon(cartel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCerrar = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        boxOp = new javax.swing.JComboBox<>();
        lblCartel = new javax.swing.JLabel();
        lblMecanico = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inicio.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        boxOp.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        boxOp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bienvenido", "¿Quiénes somos?", "Crash Car", "¿Cómo empezar?", "Jugabilidad", "Quiero reportar un error...", "Soporte" }));
        boxOp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxOpItemStateChanged(evt);
            }
        });
        getContentPane().add(boxOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 460, -1));
        getContentPane().add(lblCartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        lblMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mech2.gif"))); // NOI18N
        getContentPane().add(lblMecanico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoFAQ.gif"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxOpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxOpItemStateChanged
        // TODO add your handling code here:
        int pos;
        Icon a = null;
        pos = boxOp.getSelectedIndex();
        ImageIcon mech = new ImageIcon(getClass().getResource("/img/mech2.gif"));

        switch (pos) {
            case 0:
                ImageIcon cartel = new ImageIcon(getClass().getResource("/img/cartel1.png"));
                lblMecanico.setIcon(mech);
                lblCartel.setIcon(cartel);
                lblImg.setIcon(a);
                break;
            case 1:
                ImageIcon cartel1 = new ImageIcon(getClass().getResource("/img/cartel2.png"));
                lblMecanico.setIcon(mech);
                lblCartel.setIcon(cartel1);
                lblImg.setIcon(a);
                break;
            case 2:
                ImageIcon cartel2 = new ImageIcon(getClass().getResource("/img/cartel3.png"));
                ImageIcon juego = new ImageIcon(getClass().getResource("/img/videoJuego.gif"));
                lblMecanico.setIcon(mech);
                lblCartel.setIcon(cartel2);
                lblImg.setIcon(juego);
                break;
            case 3:
                ImageIcon cartel3 = new ImageIcon(getClass().getResource("/img/cartel4.png"));
                ImageIcon tuto = new ImageIcon(getClass().getResource("/img/tuto.gif"));
                lblMecanico.setIcon(mech);
                lblCartel.setIcon(cartel3);
                lblImg.setIcon(tuto);
                break;
            case 4:
                ImageIcon cartel4 = new ImageIcon(getClass().getResource("/img/cartel5.png"));
                ImageIcon flechas = new ImageIcon(getClass().getResource("/img/flechas2.png"));
                lblMecanico.setIcon(mech);
                lblCartel.setIcon(cartel4);
                lblImg.setIcon(flechas);
                break;
            case 5:
                ImageIcon cartel5 = new ImageIcon(getClass().getResource("/img/cartel6.png"));
                ImageIcon correo = new ImageIcon(getClass().getResource("/img/mail.gif"));
                ImageIcon srry = new ImageIcon(getClass().getResource("/img/srry.png"));
                lblMecanico.setIcon(srry);
                lblCartel.setIcon(cartel5);
                lblImg.setIcon(correo);
                break;
            case 6:
                ImageIcon cartel6 = new ImageIcon(getClass().getResource("/img/cartel7.png"));
                lblMecanico.setIcon(mech);
                lblCartel.setIcon(cartel6);
                lblImg.setIcon(a);
                break;
        }
    }//GEN-LAST:event_boxOpItemStateChanged

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        AudioClip Sound; //Sonido botón
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/audio/ClicSFX.wav"));
        Sound.play();
        frmPrincipal volver = new frmPrincipal();
        volver.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxOp;
    private javax.swing.JLabel lblCartel;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblMecanico;
    // End of variables declaration//GEN-END:variables
}
