/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import control.Control;
import control.CustomFont;
import dao.Usuario;
import java.applet.AudioClip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Flayxamax
 */
public class frmLogin extends javax.swing.JFrame {

    private Usuario usuario;
    private StringBuffer respuesta;

    /**
     * Creates new form frmLogin2
     */
    public frmLogin() {
        initComponents();
        setResizable(false);
        setTitle("Iniciar sesión");
        setIconImage(new ImageIcon(getClass().getResource("/img/iconGame.png")).getImage());
        setSize(600, 845);
        usuario = new Usuario();
        setVisible(true);
        CustomFont cf = new CustomFont();
        txtUsuario.setFont(cf.MyFont(0, 30));
        lblIniciar.setFont(cf.MyFont(0, 30));
        lblSug.setFont(cf.MyFont(0, 20));
        lblRegistrar.setFont(cf.MyFont(0, 30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCerrar = new javax.swing.JLabel();
        lblRegistrar = new javax.swing.JLabel();
        lblBotonR = new javax.swing.JLabel();
        lblIniciar = new javax.swing.JLabel();
        lblBotonI = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        lblSug = new javax.swing.JLabel();
        lblBgLogin = new javax.swing.JLabel();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inicio.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblRegistrar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(102, 102, 102));
        lblRegistrar.setText("Registrar");
        getContentPane().add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 690, 110, 30));

        lblBotonR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonGris.png"))); // NOI18N
        lblBotonR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonRMouseClicked(evt);
            }
        });
        getContentPane().add(lblBotonR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, 200, 50));

        lblIniciar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblIniciar.setForeground(new java.awt.Color(102, 102, 102));
        lblIniciar.setText("Iniciar sesión");
        getContentPane().add(lblIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 160, 30));

        lblBotonI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonGris.png"))); // NOI18N
        lblBotonI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonIMouseClicked(evt);
            }
        });
        getContentPane().add(lblBotonI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 200, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crash car.gif"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 390, 300));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 250, 32));

        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveKeyTyped(evt);
            }
        });
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 250, 34));

        lblSug.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblSug.setForeground(new java.awt.Color(255, 255, 255));
        lblSug.setText("Si no tienes cuenta, registrate:");
        getContentPane().add(lblSug, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, -1, -1));

        lblBgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        getContentPane().add(lblBgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 360, 470));

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calleBG.png"))); // NOI18N
        getContentPane().add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 890));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lblBotonIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonIMouseClicked
        // TODO add your handling code here:
        AudioClip Sound; //Sonido botón
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/audio/ClicSFX.wav"));
        Sound.play();
        if (txtUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de usuario vacio");
        }
        String clave = "";
        for (int i = 0; i < txtClave.getPassword().length; i++) {
            clave = clave + txtClave.getPassword()[i];
        }
        if (clave.equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de contraseña vacio");
        } else {
            usuario.setUsuario(txtUsuario.getText());
            usuario.setPassword(clave);
            if (control.iniciar(this, usuario)) {
                juegoPrincipal us = new juegoPrincipal();
                String usu = txtUsuario.getText();
                us.setUsuario(usu);
                juegoPrincipal juego = new juegoPrincipal();
                juego.start();

            }
            dispose();
        }
    }//GEN-LAST:event_lblBotonIMouseClicked

    private void lblBotonRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonRMouseClicked
        // TODO add your handling code here:
        AudioClip Sound; //Sonido botón
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/audio/ClicSFX.wav"));
        Sound.play();
        frmUsuarios usuarios = new frmUsuarios();
        usuarios.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBotonRMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        AudioClip Sound; //Sonido botón
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/audio/ClicSFX.wav"));
        Sound.play();
        frmPrincipal volver = new frmPrincipal();
        volver.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        // TODO add your handling code here:
        if(txtUsuario.getText().length()>=20){
            evt.consume();
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyTyped
        // TODO add your handling code here:
        if(txtClave.getPassword().length>=15){
            evt.consume();
        }
    }//GEN-LAST:event_txtClaveKeyTyped

    Control control = new Control();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblBgLogin;
    private javax.swing.JLabel lblBotonI;
    private javax.swing.JLabel lblBotonR;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblIniciar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblSug;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
